---
- name: Install and setup docker packages
  hosts: all
  become: true

  roles:
    - docker

  tasks:
    - name: Install required packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present
      tags:
        - docker

    - name: Add Docker GPG keys
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      tags:
        - docker

    - name: Verify GPG key
      apt_key:
        id: 0EBFCD88
        state: present
      tags:
        - docker

    - name: Add Docker repository for Ubuntu
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
      when: ansible_distribution == 'Ubuntu'
      tags:
        - docker

    - name: Add Docker repository for Debian
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
        state: present
      when: ansible_distribution == 'Debian'
      tags:
        - docker

    - name: Update apt packages
      apt:
        update_cache: yes
      tags:
        - docker

    - name: Install docker-ce
      apt:
        name: docker-ce
        state: present
      tags:
        - docker

    - name: Install docker-compose
      get_url:
        url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: '0755'
        checksum: sha256:2d708951d251414d32cc50b9cc46c41d09b526c25657de81e92469da587f8786
      tags:
        - docker

    - name: Add user to docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes
      tags:
        - docker
