# Define the target hosts
- hosts: all

  # Install required packages
  tasks:
    - name: Install required packages
      become: yes
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present

    # Add Docker GPG key
    - name: Add Docker GPG key
      become: yes
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        id: 0EBFCD88

    # Add Docker repository for Ubuntu
    - name: Add Docker repository for Ubuntu
      become: yes
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
        state: present
      when: ansible_distribution == 'Ubuntu'

    # Add Docker repository for Debian
    - name: Add Docker repository for Debian
      become: yes
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/debian buster stable
        state: present
      when: ansible_distribution == 'Debian'

    # Update apt packages
    - name: Update apt packages
      become: yes
      apt:
        update_cache: yes

    # Install Docker CE
    - name: Install Docker CE
      become: yes
      apt:
        name: docker-ce
        state: present

    # Install Docker Compose
    - name: Install Docker Compose
      become: yes
      get_url:
        url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: 'a+x'

    # Add the current user to the docker group
    - name: Add the current user to the docker group
      become: yes
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

  # Tag the tasks
  tags:
    - docker
