---
- name: Install and setup docker
  hosts: all
  become: true
  become_method: sudo
  tags:
    - docker

  tasks:
  - name: Install required packages
    apt:
      name:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common
      state: present
      update_cache: yes
    when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'

  - name: Add Docker GPG keys
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      id: 0EBFCD88
      state: present

  - name: Add Docker repository for Ubuntu
    apt_repository:
      repo: deb [arch=amd64,arm64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
      state: present
    when: ansible_distribution == 'Ubuntu'

  - name: Add Docker repository for Debian
    apt_repository:
      repo: deb [arch=amd64,arm64] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable
      state: present
    when: ansible_distribution == 'Debian'

  - name: Update apt packages
    apt:
      update_cache: yes

  - name: Install docker-ce
    apt:
      name: docker-ce
      state: present
      update_cache: yes

  - name: Download and Install docker-compose
    get_url:
      url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
      dest: /usr/local/bin/docker-compose
      mode: '0755'
    when: ansible_architecture == 'x86_64'
  
  - name: Add user to docker group
    user:
      name: "{{ ansible_user }}"
      groups: docker
      append: yes

  tags:
    - docker
