name: shell commands

on:
  - push 


jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: echo string
        run: echo "Pay now"
  Ansible-workflows:
    runs-on: ubuntu-22.04 
    needs: ["run-shell-commands"]
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: Ansible playbook
        run: ansible-playbook code.yml
